language: java
jdk:
- oraclejdk8

branches:
  except:
    - gh-pages

env:
  global:
  - secure: mJdyjuzEt7ywc6b4M4MgOaBbKItUvM6Fb1KwtyaZTmadakUb1c5Eikrp4xWwopmv8gs35SWwGFgOF9w4VEqtGxNXPpURmhPDy37g/wKLS4PAK12pvy/trgTCgHNX8nFXYp/Lb1N4ouBOctfAbFL493ZWqAaYXjYafWPLbcAIO0M=
  matrix:
    - TARGET_PLATFORM=indigo
    - TARGET_PLATFORM=juno
    - TARGET_PLATFORM=kepler
    - TARGET_PLATFORM=luna

before_install:
  - mvn --file org.sonatype.aether/pom.xml install

  # install latest android sdk updates and dependencies
  - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - tar -zxf android-sdk_r23.0.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null
  - echo yes |android update sdk --filter platform-tools,build-tools-21.1.0,android-18,addon-google_apis-google-18,android-10,android-7,extra-android-support,sysimg-16 --no-ui --force > /dev/null
  # install android sdk dependencies in local repo
  - git clone https://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer
  - mvn install -P 4.3
  - cd ..

  - sudo apt-get install imagemagick
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis"
  - git clone --quiet https://WonderCsabo:${GH_TOKEN}@github.com/WonderCsabo/hello.git > /dev/null
  - git checkout -b $TRAVIS_BUILD_ID.$TRAVIS_BUILD_NUMBER
  
  # start windowing session
  - sh -e /etc/init.d/xvfb start
  - import -display :99 -window root hello/screenshot.png
  - chmod +x hello.sh
  - ./hello.sh &

before_script:
  - sudo service postgresql stop
  - sudo service mysql stop
  - sudo service memcached stop
  - export DISPLAY=:99.0
  - echo adtUsed=true$'\n'lastSdkPath=$ANDROID_HOME > ~/.android/ddms.cfg
  - chmod 777 ~/.android/ddms.cfg

script: mvn -e --file me.gladwell.eclipse.m2e.android.test/pom.xml -Dtarget.platform=$TARGET_PLATFORM -Dtycho.showEclipseLog=true verify

after_success:
  - if [[ "$TARGET_PLATFORM" == "luna" ]]; then mvn -Dgithub.global.oauth2Token=$GITHUB_AUTH_TOKEN -pl me.gladwell.eclipse.m2e.android.update com.github.github:site-maven-plugin:site; fi

after_failure:
  - cd hello
  - git add .
  - git commit -m "screenshots"
  - git push --set-upstream $TRAVIS_BUILD_ID.$TRAVIS_BUILD_NUMBER origin/$TRAVIS_BUILD_ID.$TRAVIS_BUILD_NUMBER
